# Github Actions Workflow for building wheels
# The step for creating a github release is borrowed from cython
# https://github.com/cython/cython/blob/master/.github/workflows/wheels.yml
name: Build wheels

on:
  # Uncomment for testing through a PR
  # pull_request:
  #   branches: [develop, releases/**]
  workflow_dispatch:
  push:
    tags:
      - 'v**'

jobs:
  build_wheels:
    name: Build wheel for ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}
    strategy:
      fail-fast: false
      matrix:
        # GitHub Actions doesn't support pairing matrix values together, let's improvise
        # https://github.com/github/feedback/discussions/7835#discussioncomment-1769026
        buildplat:
        - [ubuntu-22.04, manylinux_x86_64]
        - [ubuntu-22.04, musllinux_x86_64]
        - [macos-12, macosx_x86_64]
        # Note: M1 images on Github Actions start from macOS 14
        - [macos-14, macosx_arm64]
        - [windows-2022, win_amd64]
        # TODO: support PyPy?
        python: [["cp39", "3.9"], ["cp310", "3.10"], ["cp311", "3.11"], ["cp312", "3.12"]]
    runs-on: ${{ matrix.buildplat[0] }}
    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_SKIP: pp* *musllinux*
          CIBW_BUILD: ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: wheelhouse/*.whl
          draft: true
          prerelease: >-
            ${{ contains(github.ref_name, 'a') || contains(github.ref_name, 'b')
              || contains(github.ref_name, 'rc') || contains(github.ref_name, 'dev') }}

  build_sdist:
    name: Build sdist
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Get PyPA build
        run: python -m pip install build

      - name: Build sdist
        run: python -m build -s

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.tar.gz
            dist/*-none-any.whl
          draft: true
          prerelease: >-
            ${{ contains(github.ref_name, 'a') || contains(github.ref_name, 'b')
              || contains(github.ref_name, 'rc') || contains(github.ref_name, 'dev') }}
